import { PDFDocument, StandardFonts, rgb, PageSizes } from 'pdf-lib'

export interface FlaggedLine {
  cptCode: string
  description: string
  charged: number
  publishedRate: number
  multiplier: number
}

export async function generateDisputeLetter(flaggedLines: FlaggedLine[]): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create()
  const font = await pdfDoc.embedFont(StandardFonts.TimesRoman)
  const boldFont = await pdfDoc.embedFont(StandardFonts.TimesRomanBold)

  const page = pdfDoc.addPage(PageSizes.Letter) // 612 x 792 points
  const { width, height } = page.getSize()
  const margin = 72 // 1 inch margins
  const lineHeight = 14
  let y = height - margin

  const draw = (text: string, opts: { bold?: boolean; size?: number } = {}) => {
    page.drawText(text, {
      x: margin,
      y,
      size: opts.size ?? 11,
      font: opts.bold ? boldFont : font,
      color: rgb(0, 0, 0),
      maxWidth: width - margin * 2,
    })
    y -= lineHeight * (opts.size ? opts.size / 11 : 1)
  }

  const skip = (lines = 1) => {
    y -= lineHeight * lines
  }

  const today = new Date().toISOString().slice(0, 10)

  draw('[YOUR NAME]')
  draw('[YOUR ADDRESS]')
  draw('[CITY, STATE ZIP]')
  skip()
  draw(today)
  skip()
  draw('Billing Department')
  draw('Memorial Regional Medical Center')
  draw('[HOSPITAL ADDRESS]')
  skip()
  draw(`RE: Dispute of Charges — Itemized Bill Dated ${today}`, { bold: true })
  skip()
  draw('Dear Billing Department,')
  skip()

  for (const line of flaggedLines) {
    const amt = `$${line.charged.toFixed(2)}`
    const pub = `$${line.publishedRate.toFixed(2)}`
    const diff = `$${(line.charged - line.publishedRate).toFixed(2)}`
    const mult = line.multiplier.toFixed(1)

    draw(`I am writing to dispute the charge for CPT code ${line.cptCode} (${line.description}).`)
    draw(`My bill shows a charge of ${amt}. Memorial Regional Medical Center's own publicly-posted`)
    draw(`chargemaster lists the rate for CPT ${line.cptCode} at ${pub} — a difference of ${diff},`)
    draw(`or ${mult} times the published rate.`)
    skip()
  }

  draw(
    'Under 45 CFR §180 (Hospital Price Transparency Final Rule), hospitals are required to publish',
  )
  draw('their standard charges for all items and services. I am requesting an immediate review and')
  draw(
    'correction of the above line items to reflect the published rates, or a written explanation',
  )
  draw('of the billing discrepancy within 30 days.')
  skip()
  draw('This letter is sent in good faith. I expect a written response within 30 days of receipt.')
  skip(2)
  draw('Sincerely,')
  skip(3)
  draw('_____________________________')
  draw('[YOUR NAME]')
  draw('[YOUR PHONE / EMAIL]')

  page.drawText(
    'This letter was generated by hightimized (hightimized.com), an open-source audit-assist tool. It is not legal advice. Consult a licensed attorney for legal guidance.',
    {
      x: margin,
      y: margin / 2,
      size: 8,
      font,
      color: rgb(0.5, 0.5, 0.5),
      maxWidth: width - margin * 2,
    },
  )

  return pdfDoc.save()
}
